version: '3.8'
services:
  postgres-gorm:
    image: postgres:latest
    ports:
      - '5435:5432'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=360339
      - POSTGRES_DB:=postgres
    networks:
      - postgres-gorm-network
networks:
  postgres-gorm-network:
    driver: bridge