POST http://localhost:8080/signup
Content-Type: application/json

{
  "name": "sasa",
  "email": "sasha_chernykh_2020@mail.ru",
  "password": "SaSHa36033",
  "role": "user"
}

###
POST http://localhost:8080/reset-password
Content-Type: application/json

{
  "token":"22307781a79acf69e01d76821d80ee89",
  "new_password": "SaSHa360339"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "sasha_chernykh_2020@mail.ru",
  "password": "SaSHa360339"
}

###
GET http://localhost:8080/home
Content-Type: application/json

{
  
}

###
POST http://localhost:8080/request-reset-password
Content-Type: application/json

{
  "email": "sasha_chernykh_2020@mail.ru"
}
